# build_and_store_wheels: &BUILD_AND_STORE_WHEELS
#   install_cibuildwheel_script:
#     - python3.9 -m pip install cibuildwheel==2.11.2
#   run_cibuildwheel_script:
#     - cibuildwheel --platform macos
#   wheels_artifacts:
#     path: "wheelhouse/*"

# macos_task:
#   name: Build macOS arm64 wheel.
#   macos_instance:
#     image: ghcr.io/cirruslabs/macos-monterey-xcode
#   env:
#     PATH: /opt/homebrew/opt/python@3.9/bin:$PATH
#     CIBW_BUILD: cp39-macosx_arm64
#   install_pre_requirements_script:
#     - brew install gcc
#     - brew install python@3.9
#     # - ln -s python3 /opt/homebrew/opt/python@3.9/bin/python
#   <<: *BUILD_AND_STORE_WHEELS