build_and_store_wheels: &BUILD_AND_STORE_WHEELS
  run_cibuildwheel_script:
    - cibuildwheel --platform macos
  wheels_artifacts:
    path: 'wheelhouse/*'

macos_arm64_cp38_task:
  name: Build macOS arm64 wheel
  trigger_type: manual
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode # NOTE Apple Silicon runner!! (arm64)
  env:
    PATH: $PATH:/opt/homebrew/opt/python@3.8/bin
    CIBW_BUILD: cp38-macosx_arm64
    CIBW_ARCHS_MACOS: arm64
    CIBW_ENVIRONMENT_MACOS: MACOSX_DEPLOYMENT_TARGET="11.0"
    CIBW_BEFORE_ALL_MACOS: >
      7z x test/demo.zip -o"test/demo" &&
      tar -xzf OpenBLAS-0.3.21.tar.gz &&
      make -C OpenBLAS-0.3.21 TARGET=ARMV8 DYNAMIC_ARCH=1
  install_pre_requirements_script:
    - brew install p7zip
    - brew install python@3.8
  install_cibuildwheel_script:
    - python3.8 -m pip install cibuildwheel==2.11.2
  <<: *BUILD_AND_STORE_WHEELS

macos_arm64_cp39_task:
  name: Build macOS arm64 wheel
  trigger_type: manual
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode # NOTE Apple Silicon runner!! (arm64)
  env:
    PATH: $PATH:/opt/homebrew/opt/python@3.9/bin
    CIBW_BUILD: cp39-macosx_arm64
    CIBW_ARCHS_MACOS: arm64
    CIBW_ENVIRONMENT_MACOS: MACOSX_DEPLOYMENT_TARGET="11.0"
    CIBW_BEFORE_ALL_MACOS: >
      7z x test/demo.zip -o"test/demo" &&
      tar -xzf OpenBLAS-0.3.21.tar.gz &&
      make -C OpenBLAS-0.3.21 TARGET=ARMV8 DYNAMIC_ARCH=1
  install_pre_requirements_script:
    - brew install p7zip
    - brew install python@3.9
  install_cibuildwheel_script:
    - python3.9 -m pip install cibuildwheel==2.11.2
  <<: *BUILD_AND_STORE_WHEELS

macos_arm64_cp310_task:
  name: Build macOS arm64 wheel
  trigger_type: manual
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode # NOTE Apple Silicon runner!! (arm64)
  env:
    PATH: $PATH:/opt/homebrew/opt/python@3.10/bin
    CIBW_BUILD: cp310-macosx_arm64
    CIBW_ARCHS_MACOS: arm64
    CIBW_ENVIRONMENT_MACOS: MACOSX_DEPLOYMENT_TARGET="11.0"
    CIBW_BEFORE_ALL_MACOS: >
      7z x test/demo.zip -o"test/demo" &&
      tar -xzf OpenBLAS-0.3.21.tar.gz &&
      make -C OpenBLAS-0.3.21 TARGET=ARMV8 DYNAMIC_ARCH=1
  install_pre_requirements_script:
    - brew install p7zip
    - brew install python@3.10
  install_cibuildwheel_script:
    - python3.10 -m pip install cibuildwheel==2.11.2
  <<: *BUILD_AND_STORE_WHEELS
