build_and_store_wheels: &BUILD_AND_STORE_WHEELS
  install_cibuildwheel_script:
    - python3 -m pip install cibuildwheel==2.11.2
  run_cibuildwheel_script:
    - cibuildwheel
  wheels_artifacts:
    path: "wheelhouse/*"

macos_task:
  name: Build macOS x86_64 and arm64 wheels.
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode
  env:
    PATH: /opt/homebrew/opt/python@3.9/bin:$PATH
  install_pre_requirements_script:
    - brew install python@3.9
    - brew install gcc
  <<: *BUILD_AND_STORE_WHEELS