# TODO badges
# TODO trigger from github
# TODO add name and alias
compile_OpenBLAS_macos_task:
  trigger_type: manual
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode
  env:
    MACOSX_DEPLOYMENT_TARGET: "11.0"
  clone_script: # TODO name Clone?
    - echo SKIP CLONE
  install_requirements_script:
    - brew install p7zip
  compile_OpenBLAS_arm64_script:
    - curl -L -o OpenBLAS-0.3.21.tar.gz https://github.com/xianyi/OpenBLAS/releases/download/v0.3.21/OpenBLAS-0.3.21.tar.gz
    - tar -xzf OpenBLAS-0.3.21.tar.gz
    - make -C OpenBLAS-0.3.21 TARGET=ARMV8 DYNAMIC_ARCH=1
    - make install -C OpenBLAS-0.3.21 PREFIX=$(pwd)/OpenBLAS
    - 7z a OpenBLAS_macos_arm64.zip ./OpenBLAS/*
  compiled_OpenBLAS_artifacts:
    path: 'OpenBLAS_macos_arm64.zip'

build_macos_wheels_task:
  name: Build MacOS wheels
  alias: build_macos_wheels
  trigger_type: manual
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode
  matrix: # TODO env: matrix https://cirrus-ci.org/guide/writing-tasks/#task-execution-dependencies
    - env:
        PY: "3.8"
        CP: "38"
    - env:
        PY: "3.9"
        CP: "39"
    - env:
        PY: "3.10"
        CP: "310"
  env:
    PATH: $PATH:/opt/homebrew/opt/python@${PY}/bin
    CIBW_PLATFORM: macos
    CIBW_BUILD: cp${CP}-macosx_arm64
    CIBW_ARCHS_MACOS: arm64
    CIBW_ENVIRONMENT_MACOS: MACOSX_DEPLOYMENT_TARGET="11.0" OPENBLAS_DIR="$(pwd)/OpenBLAS"
    CIBW_BEFORE_ALL_MACOS: >
      7z x test/demo.zip -o"test/demo"
  install_requirements_script:
    - brew install p7zip
    - brew install python@${PY}
    - python${PY} -m pip install cibuildwheel==2.11.2 # TODO update
  download_compiled_OpenBLAS_script:
    - curl -L -o OpenBLAS.zip https://api.cirrus-ci.com/v1/artifact/build/4925916816605184/compile_OpenBLAS_macos/compiled_OpenBLAS/OpenBLAS_macos_arm64.zip # TODO build number as cirrus env variable (set after build)
    - 7z x OpenBLAS.zip -o"OpenBLAS"
  run_cibuildwheel_script:
    - cibuildwheel
  wheels_macos_arm64_artifacts:
    path: './wheelhouse/*.whl' # TODO gh ation to download this? send a trigger?

trigger_github_task:
  name: Trigger GitHub job
  depends_on: build_macos_wheels
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode
  env:
    DOWNLOAD_TOKEN: ENCRYPTED[7ba2ebb239bb262692229ed57489df90a2dd20809c62574bbdeee56335ed645012913b6a0a3462ecaef5f91484dfbaed]
  clone_script:
    - echo SKIP
  # TODO view here https://towardsdatascience.com/proper-ways-to-pass-environment-variables-in-json-for-curl-post-f797d2698bf3
  download_script:
    # - curl -X POST -H "Accept:application/vnd.github+json" -H "Authorization:Bearer ${DOWNLOAD_TOKEN}" -H "X-GitHub-Api-Version:2022-11-28" https://api.github.com/repos/nightwnvol/amico_gh_actions/dispatches -d '{"event_type":"test_download","client_payload":{"passed":true,"build_id":"'"$CIRRUS_BUILD_ID"'"}}'
    - curl -X POST -H "Accept:application/vnd.github+json" -H "Authorization:Bearer ${DOWNLOAD_TOKEN}" -H "X-GitHub-Api-Version:2022-11-28" https://api.github.com/repos/nightwnvol/amico_gh_actions/dispatches -d '{"event_type":"test_download","client_payload":{"passed":true,"build_id":5565913148162048}}'

# macos_arm64_wheels_task:
#   name: MacOS (arm64) wheels
#   trigger_type: manual
#   macos_instance:
#     image: ghcr.io/cirruslabs/macos-monterey-xcode
#   matrix:
#     - env:
#         PY: "3.8"
#         CP: "38"
#     - env:
#         PY: "3.9"
#         CP: "39"
#     - env:
#         PY: "3.10"
#         CP: "310"
#   env:
#     PATH: $PATH:/opt/homebrew/opt/python@${PY}/bin
#     CIBW_PLATFORM: macos
#     CIBW_BUILD: cp${CP}-macosx_arm64
#     CIBW_ARCHS_MACOS: arm64
#     CIBW_ENVIRONMENT_MACOS: MACOSX_DEPLOYMENT_TARGET="11.0" OPENBLAS_DIR="$(pwd)/OpenBLAS"
#     CIBW_BEFORE_ALL_MACOS: >
#       7z x test/demo.zip -o"test/demo" &&
#       curl -L -o OpenBLAS-0.3.21.tar.gz https://github.com/xianyi/OpenBLAS/releases/download/v0.3.21/OpenBLAS-0.3.21.tar.gz &&
#       tar -xzf OpenBLAS-0.3.21.tar.gz &&
#       make -C OpenBLAS-0.3.21 TARGET=ARMV8 DYNAMIC_ARCH=1 &&
#       make install -C OpenBLAS-0.3.21 PREFIX=$(pwd)/OpenBLAS
#   install_pre_requirements_script:
#     - brew install p7zip
#     - brew install python@${PY}
#   install_cibuildwheel_script:
#     - python${PY} -m pip install cibuildwheel==2.11.2
#   run_cibuildwheel_script:
#     - cibuildwheel
#   wheels_artifacts:
#     path: 'wheelhouse/*'
