build_and_store_wheels: &BUILD_AND_STORE_WHEELS
  install_cibuildwheel_script:
    - python3 -m pip install cibuildwheel==2.11.2
  run_cibuildwheel_script:
    - cibuildwheel --platform macos
  wheels_artifacts:
    path: 'wheelhouse/*'

build_macos_cp39_task:
  name: Build macOS arm64 cp39 wheel
  trigger_type: manual
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode # Apple Silicon runner!! (arm64)
  env:
    PATH: $PATH:/opt/homebrew/opt/python@3.9/bin
    CIBW_BUILD: cp39-macosx_arm64
  install_pre_requirements_script:
    - brew install gcc
    - brew install python@3.9
  <<: *BUILD_AND_STORE_WHEELS

build_macos_cp311_task:
  name: Build macOS arm64 cp311 wheel
  trigger_type: manual
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode # Apple Silicon runner!! (arm64)
  env:
    PATH: $PATH:/opt/homebrew/opt/python@3.11/bin
    CIBW_BUILD: cp311-macosx_arm64
  install_pre_requirements_script:
    - brew install gcc
    - brew install python@3.11
  <<: *BUILD_AND_STORE_WHEELS
