[build-system]
requires = [
    "setuptools",
    "Cython>=0.29.32",
    "cyspams @ git+https://github.com/getspams/spams-cython.git@test_cp36"
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
test-command = "python -m pip install -U pip && pip list && pip show dmri-amico -v && python {project}/test/noddi.py"
test-skip = "*-win32 cp38-macosx_arm64 *-manylinux_aarch64"
build-verbosity = 3

# [tool.cibuildwheel.windows]
# before-build = "pip install delvewheel"
# repair-wheel-command = "delvewheel repair --add-path %cd%\\OpenBLAS\\bin -w {dest_dir} -v {wheel}"

# [tool.cibuildwheel.macos]
# repair-wheel-command = "DYLD_LIBRARY_PATH=$(pwd)/OpenBLAS/lib delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel}"

# [tool.cibuildwheel.linux]
# repair-wheel-command = "LD_LIBRARY_PATH=$(pwd)/OpenBLAS/lib auditwheel repair -w {dest_dir} {wheel}"
