[build-system]
requires = ["setuptools", "Cython"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
test-command = "python {project}/test/noddi.py"
test-skip = "*-win32 cp38-macosx_arm64"
build-verbosity = 3

[tool.cibuildwheel.windows]
before-build = "pip install delvewheel"
repair-wheel-command = "delvewheel repair --add-path OpenBLAS-0.3.21\\bin -w {dest_dir} {wheel}"
before-test = "7z x test/demo.zip -otest/demo"

[tool.cibuildwheel.macos]
environment = "REPAIR_LIBRARY_PATH='$(pwd)/OpenBLAS-0.3.21'"
before-all = [
    "tar -xzf OpenBLAS-0.3.21.tar.gz",
    "make -C OpenBLAS-0.3.21 DYNAMIC_ARCH=1"
]
repair-wheel-command = "DYLD_LIBRARY_PATH=$REPAIR_LIBRARY_PATH delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel}"
before-test = "7z x test/demo.zip -otest/demo"

[tool.cibuildwheel.linux]
environment = "LD_LIBRARY_PATH='$(pwd)/OpenBLAS-0.3.21'"
before-all = [
    "tar -xzf OpenBLAS-0.3.21.tar.gz",
    "make -C OpenBLAS-0.3.21 DYNAMIC_ARCH=1"
]
before-test = "unzip test/demo.zip -d test/demo"
