[build-system]
requires = ["setuptools", "Cython"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
test-command = "python {project}/test/noddi.py"
test-skip = "*-win32 cp38-macosx_arm64"
build-verbosity = 3

[tool.cibuildwheel.windows]
before-build = "pip install delvewheel"
repair-wheel-command = "delvewheel repair --add-path .\\OpenBLAS-0.3.21\\bin -w {dest_dir} -v {wheel}"

[tool.cibuildwheel.macos]
repair-wheel-command = "DYLD_LIBRARY_PATH=$(pwd)/OpenBLAS-0.3.21 delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel}"

[tool.cibuildwheel.linux]
repair-wheel-command = "LD_LIBRARY_PATH=$(pwd)/OpenBLAS-0.3.21 auditwheel repair -w {dest_dir} {wheel}"
