name: Build Windows and Linux wheels (x64)
on: workflow_dispatch
jobs:
  build_wheels:
    strategy:
      matrix:
        py: [cp37, cp38, cp39, cp310]
        plat:
          - [ubuntu-20.04, manylinux, x86_64]
          - [windows-2019, win, amd64]
          - [macos-11, macosx, x86_64]
    name: Build wheels
    runs-on: ${{ matrix.plat[0] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        if: matrix.plat[0] == 'ubuntu-20.04'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64
      - name: MacOS requirements
        if: matrix.plat[0] == 'macos-11'
        run: |
          brew install gcc
          brew install p7zip
          brew install python@3.7
          brew install python@3.8
          brew install python@3.9
          brew install python@3.10
      - name: Build
        continue-on-error: true
        uses: pypa/cibuildwheel@v2.11.2
        env:
          CIBW_BUILD: ${{ matrix.py }}-${{ matrix.plat[1] }}_${{ matrix.plat[2] }}
          CIBW_ARCHS_WINDOWS: "AMD64"
          CIBW_ARCHS_MACOS: "x86_64"
          CIBW_ARCHS_LINUX: "x86_64"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
