name: Build Windows and Linux wheels (x64)
on: workflow_dispatch
jobs:
  build_wheels:
    strategy:
      matrix:
        py: [cp38, cp39, cp310, cp311]
        plat:
          - [ubuntu-20.04, manylinux, x86_64]
          - [windows-2019, win, amd64]
          # - [macos-11, macosx, x86_64] # .cirrus.yml
    name: Build wheels
    runs-on: ${{ matrix.plat[0] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        if: matrix.plat[0] == 'ubuntu-20.04'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64
      - name: Build
        uses: pypa/cibuildwheel@v2.11.2
        env:
          CIBW_BUILD: ${{ matrix.py }}-${{ matrix.plat[1] }}_${{ matrix.plat[2] }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
