name: Build Linux no OpenBLAS
on: workflow_dispatch
jobs:
  linux_wheels:
    strategy:
      matrix:
        py: [cp37, cp38, cp39, cp310]
        arch:
          - [x86_64, manylinux_x86_64, amd64]
          - [aarch64, manylinux_aarch64, arm64]
    name: Linux wheels
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download compiled OpenBLAS artifact
        id: dowload-openblas-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          # Optional, GitHub token, a Personal Access Token with `public_repo` scope if needed
          # Required, if the artifact is from a different repo
          # Required, if the repo is private a Personal Access Token with `repo` scope is needed
          # github_token: ${{secrets.GITHUB_TOKEN}}

          # Optional, workflow file name or ID
          # If not specified, will be inferred from run_id (if run_id is specified), or will be the current workflow
          workflow: compile_ob_linux.yml

          # Optional, the status or conclusion of a completed workflow to search for
          # Can be one of a workflow conclusion:
          #   "failure", "success", "neutral", "cancelled", "skipped", "timed_out", "action_required"
          # Or a workflow status:
          #   "completed", "in_progress", "queued"
          # Use the empty string ("") to ignore status or conclusion in the search
          workflow_conclusion: success

          # Optional, will get head commit SHA
          # pr: ${{github.event.pull_request.number}}

          # Optional, no need to specify if PR is
          commit: ${{github.event.pull_request.head.sha}}

          # Optional, will use the specified branch. Defaults to all branches
          branch: main

          # Optional, defaults to all types
          # event: push

          # Optional, will use specified workflow run
          # run_id: 1122334455

          # Optional, run number from the workflow
          run_number: 37

          # Optional, uploaded artifact name,
          # will download all artifacts if not specified
          # and extract them into respective subdirectories
          # https://github.com/actions/download-artifact#download-all-artifacts
          name: OpenBLAS

          # Optional, a directory where to extract artifact(s), defaults to the current directory
          path: OpenBLAS

          # Optional, defaults to current repo
          # repo: ${{ github.repository }}

          # Optional, check the workflow run to whether it has an artifact
          # then will get the last available artifact from the previous workflow
          # default false, just try to download from the last one
          # check_artifacts:  false

          # Optional, search for the last workflow run whose stored an artifact named as in `name` input
          # default false
          # search_artifacts: false

          # Optional, choose to skip unpacking the downloaded artifact(s)
          # default false
          # skip_unpack: false

          # Optional, choose how to exit the action if no artifact is found
          # can be one of:
          #  "fail", "warn", "ignore"
          # default fail
          if_no_artifact_found: fail

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ matrix.arch[2] }}

      - name: Build wheel (${{ matrix.arch[0] }}, ${{ matrix.py }})
        # continue-on-error: true # TODO false
        uses: pypa/cibuildwheel@v2.11.2
        env:
          CIBW_PLATFORM: linux
          CIBW_BUILD: ${{ matrix.py }}-${{ matrix.arch[1] }}
          CIBW_ARCHS_LINUX: ${{ matrix.arch[0] }}
          CIBW_ENVIRONMENT_LINUX: OPENBLAS_DIR="$(pwd)/OpenBLAS"
          CIBW_BEFORE_ALL_LINUX: >
            unzip test/demo.zip -d test/demo
            echo CIAO
            ls -l
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
