name: Compile OpenBLAS on MacOS
on:
  workflow_call:
    outputs:
      output1:
        description: "Compiled OpenBLAS"
        value: ${{ jobs.ob_linux_x86_64.outputs.output1 }}
jobs:
  ob_linux_x86_64:
    name: Compile OpenBLAS on MacOS x86_64
    runs-on: macos-11
    outputs:
      output1: ${{ steps.compile.outputs.compiled }}

    steps:
      - name: Compile
      - id: compile
        run: |
          curl -L -o OpenBLAS-0.3.21.tar.gz https://github.com/xianyi/OpenBLAS/releases/download/v0.3.21/OpenBLAS-0.3.21.tar.gz
          tar -xzf OpenBLAS-0.3.21.tar.gz
          make -C OpenBLAS-0.3.21 TARGET=SANDYBRIDGE DYNAMIC_ARCH=1
          make install -C OpenBLAS-0.3.21 PREFIX=$PWD/OpenBLAS

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./OpenBLAS
