name: Compile OpenBLAS on Linux
on: workflow_dispatch
jobs:
  OpenBLAS_macos_x86_64:
    name: Linux aarch64
    runs-on: ubuntu-20.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      
      - name: Run Docker
        run: |
          docker create --name=openblas_aarch64 --interactive --volume=/:/host quay.io/pypa/manylinux2014_aarch64:latest /bin/bash
          docker start --attach --interactive openblas_aarch64
          docker container ls
          docker container ls -a
          docker exec -i openblas_aarch64 sh -c "curl -L -o OpenBLAS-0.3.21.tar.gz https://github.com/xianyi/OpenBLAS/releases/download/v0.3.21/OpenBLAS-0.3.21.tar.gz"
          docker exec -i openblas_aarch64 sh -c "tar -xzf OpenBLAS-0.3.21.tar.gz"
          docker exec -i openblas_aarch64 sh -c "make -C OpenBLAS-0.3.21 TARGET=ARMV8 DYNAMIC_ARCH=1"
