name: Compile OpenBLAS on MacOS
on: workflow_dispatch
jobs:
  compile_OpenBLAS:
    strategy:
      matrix:
        arch:
          - [x86_64, SANDYBRIDGE]
    name: ${{ matrix.arch[0] }}
    runs-on: macos-11
    steps:
      - name: Compile OpenBLAS
        env:
          MACOSX_DEPLOYMENT_TARGET: "10.9"
        run: |
          curl -L -o OpenBLAS-0.3.21.tar.gz https://github.com/xianyi/OpenBLAS/releases/download/v0.3.21/OpenBLAS-0.3.21.tar.gz
          tar -xzf OpenBLAS-0.3.21.tar.gz
          make -C OpenBLAS-0.3.21 TARGET=${{ matrix.arch[1] }} DYNAMIC_ARCH=1
          make install -C OpenBLAS-0.3.21 PREFIX=$PWD/OpenBLAS

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: OpenBLAS_macos_${{ matrix.arch[0] }}
          path: ./OpenBLAS
