name: Compile OpenBLAS on Linux
on: workflow_dispatch
jobs:
  OpenBLAS_macos_x86_64:
    name: Linux aarch64
    runs-on: ubuntu-20.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      
      - name: Run Docker
        run: |
          docker create --name=openblas_aarch64 -i -t --volume=/:/host quay.io/pypa/manylinux2014_aarch64:latest
          docker start --attach -i openblas_aarch64
          echo hello
          curl -L -o OpenBLAS-0.3.21.tar.gz https://github.com/xianyi/OpenBLAS/releases/download/v0.3.21/OpenBLAS-0.3.21.tar.gz
          tar -xzf OpenBLAS-0.3.21.tar.gz
          make -C OpenBLAS-0.3.21 TARGET=ARMV8 DYNAMIC_ARCH=1
