# TODO put this in build_macos_wheels.yml

name: Download MacOS arm64 wheels
on:
  repository_dispatch:
    types: [test_download] # TODO change name
jobs:
  download_wheels:
    name: arm64 # TODO change name?
    if: ${{ github.event.client_payload.passed }}
    runs-on: ubuntu-20.04
    steps:
      # TODO github.event.client_payload.build_id
      # - name: Download from Cirrus CI
      #   run: |
      #     mkdir wheelhouse
      #     for FILENAME in {0..${{ github.event.client_payload.n_files }}};
      #     do 
      #     curl -L -o ./wheelhouse/${{ github.event.client_payload.filenames[0] }} https://api.cirrus-ci.com/v1/artifact/build/5438263297572864/MacOS%20%28arm64%29%20wheels%20no%20OpenBLAS/wheels/wheelhouse/${{ github.event.client_payload.filenames[0] }}
      #     curl -L -o ./wheelhouse/${{ github.event.client_payload.filenames[1] }} https://api.cirrus-ci.com/v1/artifact/build/5438263297572864/MacOS%20%28arm64%29%20wheels%20no%20OpenBLAS/wheels/wheelhouse/${{ github.event.client_payload.filenames[1] }}
      #     curl -L -o ./wheelhouse/${{ github.event.client_payload.filenames[2] }} https://api.cirrus-ci.com/v1/artifact/build/5438263297572864/MacOS%20%28arm64%29%20wheels%20no%20OpenBLAS/wheels/wheelhouse/${{ github.event.client_payload.filenames[2] }}
      - name: Download from Cirrus CI
        run: |
          mkdir wheelhouse
          curl -L -o wheelhouse.zip https://api.cirrus-ci.com/v1/artifact/build/5438263297572864/MacOS%20%28arm64%29%20wheels%20no%20OpenBLAS/wheels/wheelhouse.zip
          unzip wheelhouse.zip -d wheelhouse
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels_macos_arm64
          path: ./wheelhouse/*.whl
