name: Download MacOS arm64 wheels
run-name: Download MacOS arm64 wheels on branch '${{ github.ref_name }}'
on:
  repository_dispatch:
    types: [macos_arm64_wheels]
jobs:
  download_wheels:
    name: arm64 # TODO change name?
    if: ${{ github.event.client_payload.passed }} # TODO: add github.ref_name == 'main'
    runs-on: ubuntu-20.04
    steps:
      - name: Download from Cirrus CI
        run: |
          curl -L -o wheels_macos_arm64.zip https://api.cirrus-ci.com/v1/artifact/build/${{ github.event.client_payload.build_id }}/build_macos_wheels/wheels_macos_arm64.zip
          unzip wheels_macos_arm64.zip
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels_macos_arm64
          path: ./wheelhouse/*.whl
