name: Download MacOS arm64 wheels
on:
  repository_dispatch:
    types: [test_download]
jobs:
  download_wheels:
    name: arm64
    if: ${{ github.event.client_payload.passed }}
    runs-on: ubuntu-20.04
    steps:
      - name: Download from Cirrus CI
        run: |
          curl -L -o ${{ github.event.client_payload.filename }} https://api.cirrus-ci.com/v1/artifact/build/4562732133908480/Build%20MacOS%20wheels/wheels_macos_arm64/wheelhouse/${{ github.event.client_payload.filename[0] }}
          curl -L -o ${{ github.event.client_payload.filename }} https://api.cirrus-ci.com/v1/artifact/build/4562732133908480/Build%20MacOS%20wheels/wheels_macos_arm64/wheelhouse/${{ github.event.client_payload.filename[1] }}
          curl -L -o ${{ github.event.client_payload.filename }} https://api.cirrus-ci.com/v1/artifact/build/4562732133908480/Build%20MacOS%20wheels/wheels_macos_arm64/wheelhouse/${{ github.event.client_payload.filename[2] }}
          ls -l
          mkdir wheelhouse
          mv ${{ github.event.client_payload.filename[0] }} wheelhouse/
          mv ${{ github.event.client_payload.filename[1] }} wheelhouse/
          mv ${{ github.event.client_payload.filename[2] }} wheelhouse/
          ls -l wheelhouse
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels_macos_arm64
          path: ./wheelhouse/*.whl
