# TODO: check all names
name: Download MacOS arm64 wheels
run-name: Download MacOS arm64 wheels on branch '${{ github.ref_name }}'
on:
  workflow_dispatch:
    inputs:
      cirrus_build_id:
        description: 'CirrusCI build ID'
        required: true
        type: number
      check_id_macos_arm64:
        description: Check ID MacOS arm64
        required: true
        type: number
jobs:
  macos_arm64_wheels:
    name: '*-macosx_arm64'
    runs-on: ubuntu-20.04
    steps:
      - name: Download from Cirrus CI
        run: |
          echo "res=$(curl -L -o wheels_macos_arm64.zip -w '%{http_code}' https://api.cirrus-ci.com/v1/artifact/build/${{ inputs.cirrus_build_id }}/build_macos_wheels/wheels_macos_arm64.zip)" >> $GITHUB_ENV
          7z x wheels_macos_arm64.zip

      - name: Upload artifacts
        id: upload_artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels_macos_arm64
          path: ./wheelhouse/*.whl
          if-no-files-found: error

      - name: Complete MacOS arm64 check
        if: env.res == 200 && steps.upload_artifacts.conclusion == 'success'
        run: |
          curl -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ github.token }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/nightwnvol/amico_gh_actions/check-runs/${{ inputs.check_id_macos_arm64 }} -d '{"name":"cp*-macosx_arm64","status":"completed","conclusion":"success"}'

      - name: Complete MacOS arm64 check
        if: (failure() && steps.upload_artifacts.conclusion != 'success') || env.res != 200
        run: |
          curl -X PATCH -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ github.token }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/nightwnvol/amico_gh_actions/check-runs/${{ inputs.check_id_macos_arm64 }} -d '{"name":"cp*-macosx_arm64","status":"completed","conclusion":"failure"}'

  upload_wheels:
    needs: [macos_arm64_wheels]
    # if: ${{ github.ref_name == 'main' }}
    name: Upload MacOS arm64 wheels
    runs-on: ubuntu-20.04
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: List dir
        run: |
          ls -l
          ls -l artifacts/*

      # - name: Publish package to PyPI Test
      #   uses: pypa/gh-action-pypi-publish@v1.6.4
      #   with:
      #     password: ${{ secrets.TEST_PYPI_API_TOKEN }}
      #     repository_url: https://test.pypi.org/legacy/
      #     packages_dir: artifacts/**
