name: Download MacOS arm64 wheels
run-name: Download MacOS arm64 wheels on branch '${{ github.ref_name }}'
on:
  workflow_dispatch:
    inputs:
      cirrus_build_id:
        description: 'CirrusCI build ID'
        required: true
        type: number
      passed:
        description: 'Result of the CirrusCI build'
        required: true
        type: boolean
jobs:
  download_wheels:
    name: arm64 # TODO change name?
    if: ${{ inputs.passed }} # TODO: add github.ref_name == 'main'
    runs-on: ubuntu-20.04
    # TODO: use 7z
    steps:
      - name: Download from Cirrus CI
        run: |
          curl -L -o wheels_macos_arm64.zip https://api.cirrus-ci.com/v1/artifact/build/${{ inputs.build_id }}/build_macos_wheels/wheels_macos_arm64.zip
          unzip wheels_macos_arm64.zip
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels_macos_arm64
          path: ./wheelhouse/*.whl
