# TODO put this in build_macos_wheels.yml -> NOT POSSIBLE

name: Download MacOS arm64 wheels
on: workflow_dispatch
  inputs:
    passed: false
    build_id: 0
  # repository_dispatch:
  #   types: [test_download] # TODO change name
jobs:
  download_wheels:
    name: arm64 # TODO change name?
    if: ${{ inputs.passed }}
    runs-on: ubuntu-20.04
    steps:
      # NOTE curl -L -o wheels.zip https://api.cirrus-ci.com/v1/artifact/build/5438263297572864/MacOS%20%28arm64%29%20wheels%20no%20OpenBLAS/wheels.zip
      # NOTE use alias below instead of Build%20MacOS%20wheels
      - name: Download from Cirrus CI
        run: |
          curl -L -o wheels_macos_arm64.zip https://api.cirrus-ci.com/v1/artifact/build/${{ inputs.build_id }}/build_macos_wheels/wheels_macos_arm64.zip
          unzip wheels_macos_arm64.zip
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels_macos_arm64
          path: ./wheelhouse/*.whl
