name: Linux wheels
on: workflow_dispatch
jobs:
  build_wheels:
    strategy:
      matrix:
        py: [cp36, cp37, cp38, cp39, cp310]
        arch:
          - [x86_64, manylinux_x86_64, amd64, HASWELL]
          - [aarch64, manylinux_aarch64, arm64, ARMV8]
    name: Build wheel
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ matrix.arch[2] }}

      - name: Build wheel (${{ matrix.arch[0] }}, ${{ matrix.py }})
        # continue-on-error: true
        uses: pypa/cibuildwheel@v2.11.2
        env:
          CIBW_PLATFORM: linux
          CIBW_BUILD: ${{ matrix.py }}-${{ matrix.arch[1] }}
          CIBW_ARCHS_LINUX: ${{ matrix.arch[0] }}
          CIBW_BEFORE_ALL_LINUX: >
            unzip test/demo.zip -d test/demo &&
            curl -L -o OpenBLAS-0.3.21.tar.gz https://github.com/xianyi/OpenBLAS/releases/download/v0.3.21/OpenBLAS-0.3.21.tar.gz &&
            tar -xzf OpenBLAS-0.3.21.tar.gz &&
            make -C OpenBLAS-0.3.21 TARGET=${{ matrix.arch[3] }} DYNAMIC_ARCH=1
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
