name: Linux wheels
on: workflow_dispatch
jobs:
  build_wheels:
    strategy:
      matrix:
        py: [cp36, cp37, cp38, cp39, cp310]
        plat:
          - [manylinux_x86_64, x86_64]
          - [manylinux_aarch64, aarch64]
    name: Build wheels
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      
      - name: Build wheels (x86_64)
        if: matrix.plat[1] == 'x86_64' # NOTE when you use expressions in an if conditional, you may omit the expression syntax ${{ }}
        continue-on-error: true
        uses: pypa/cibuildwheel@v2.11.2
        env:
          CIBW_BUILD: ${{ matrix.py }}-${{ matrix.plat[0] }}
          CIBW_ARCHS_LINUX: ${{ matrix.plat[1] }}
          CIBW_BEFORE_ALL_LINUX: >
            tar -xzf OpenBLAS-0.3.21.tar.gz &&
            make -C OpenBLAS-0.3.21 TARGET=HASWELL DYNAMIC_ARCH=1

      - name: Build wheels (aarch64)
        if: matrix.plat[1] == 'aarch64' # NOTE when you use expressions in an if conditional, you may omit the expression syntax ${{ }}
        continue-on-error: true
        uses: pypa/cibuildwheel@v2.11.2
        env:
          CIBW_BUILD: ${{ matrix.py }}-${{ matrix.plat[0] }}
          CIBW_ARCHS_LINUX: ${{ matrix.plat[1] }}
          CIBW_BEFORE_ALL_LINUX: >
            tar -xzf OpenBLAS-0.3.21.tar.gz &&
            make -C OpenBLAS-0.3.21 TARGET=ARMV8 DYNAMIC_ARCH=1
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
