name: MacOS wheels
on: workflow_dispatch
jobs:
  build_wheels:
    strategy:
      matrix:
        py: [cp36, cp37, cp38, cp39, cp310]
        arch:
          - [x86_64, macosx_x86_64, SANDYBRIDGE]
    name: Build wheel
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build wheel (${{ matrix.arch[0] }}, ${{ matrix.py }})
        # continue-on-error: true
        uses: pypa/cibuildwheel@v2.11.2
        env:
          CIBW_PLATFORM: macos
          CIBW_BUILD: ${{ matrix.py }}-${{ matrix.arch[1] }}
          CIBW_ARCHS_MACOS: ${{ matrix.arch[0] }}
          CIBW_ENVIRONMENT_MACOS: MACOSX_DEPLOYMENT_TARGET="10.9"
          CIBW_BEFORE_ALL_MACOS: >
            7z x test/demo.zip -o"test/demo" &&
            tar -xzf OpenBLAS-0.3.21.tar.gz &&
            make -C OpenBLAS-0.3.21 TARGET=${{ matrix.arch[2] }} DYNAMIC_ARCH=1
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
