name: Test
on: workflow_dispatch
jobs:
  test:
    runs-on: windows-2019
    steps:
      - name: Test env
        env:
          TVAR: "$(pwd)/OpenBLAS"
        shell: cmd
        run: |
          echo %TVAR%
