name: Test AMICO on Windows (x64)
on: workflow_dispatch
jobs:
  build_and_test:
    strategy:
      matrix:
        py: [cp39]
        plat:
          - [windows-2019, win, amd64]
    name: Build wheels
    runs-on: ${{ matrix.plat[0] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: pypa/cibuildwheel@v2.11.2
        env:
          CIBW_BUILD: ${{ matrix.py }}-${{ matrix.plat[1] }}_${{ matrix.plat[2] }}
