name: Windows wheels new
on: workflow_dispatch
jobs:
  build_wheels:
    strategy:
      matrix:
        arch:
          - [AMD64, win_amd64]
          - [x86, win32]
    name: Build wheels
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up OpenBLAS (AMD64)
        if: matrix.arch[0] == 'AMD64' # NOTE when you use expressions in an if conditional, you may omit the expression syntax ${{ }}
        run: 7z x OpenBLAS-0.3.21-x64.zip -o"OpenBLAS-0.3.21"

      - name: Set up OpenBLAS (x86)
        if: matrix.arch[0] == 'x86' # NOTE when you use expressions in an if conditional, you may omit the expression syntax ${{ }}
        run: 7z x OpenBLAS-0.3.21-x86.zip -o"OpenBLAS-0.3.21"

      - name: Set up test
        run: 7z x test/demo.zip -otest/demo

      - name: Build wheels (${{ matrix.arch[0] }})
        # continue-on-error: true
        uses: pypa/cibuildwheel@v2.11.2
        env:
          # CIBW_BUILD: cp36-${{ matrix.arch[1] }} cp37-${{ matrix.arch[1] }} cp38-${{ matrix.arch[1] }} cp39-${{ matrix.arch[1] }} cp310-${{ matrix.arch[1] }}
          CIBW_BUILD: "{cp36,cp37,cp38,cp39,cp310}-${{ matrix.arch[1] }}" # TODO to test
          CIBW_ARCHS_WINDOWS: ${{ matrix.arch[0] }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
